### PR TITLE
Update to v0.6 API

### LINKED ISSUE #11: Update to new v0.6 API
We made some (breaking) changes to the API, this needs to be reflected here.

### PR DESCRIPTION
**Pull request by lissyx**
Fixes #11

### CODE REVIEW

**Comment by lissyx** [comment]
@asticode You should be able to use https://github.com/lissyx/DeepSpeech/releases/download/tc-0.6.0/models.tar.gz for testing if required

**Comment by asticode** [comment]
That looks good to me.

However mentions of v0.5.1 should be replaced by v0.6.0 in the doc.

By the way, do you know when v0.6.0 will be released?

**Comment by lissyx** [comment]
> However mentions of v0.5.1 should be replaced by v0.6.0 in the doc.

Done

> By the way, do you know when v0.6.0 will be released?

Not yet, but that should be rather soon

**Comment by asticode** [comment]
OK, this PR looks perfect.

However I'd rather wait for the `v0.6.0` release to come out.

Do you mind pinging here when it does?

**Comment by lissyx** [comment]
> Do you mind pinging here when it does?

Sure

**Comment by asticode** [comment]
Great!

I'll merge it then.

Cheers

**Comment by lissyx** [comment]
We'll have a few more changes to fold, as we decided to simplify some other part. It's just a useless parameter removal, so no biggies.

**Comment by lissyx** [comment]
@asticode Sorry about the noise, but following the removal of useless parameter, we extended the API to allow clients to read the sample rate of the model. Latest push should cover that. It builds and runs correctly here.

**Comment by lissyx** [comment]
@asticode This should be the last alpha we make, with more API simplifications.

**Comment by lissyx** [comment]
@asticode Gentle ping, v0.6 is out :) https://github.com/mozilla/DeepSpeech/releases/tag/v0.6.0

**Comment by asticode** [comment]
Nice ! Have you checked that everything builds and runs correctly with the new release ?

**Comment by lissyx** [comment]
I did back then and we made no breaking changes since. I can't test before a few days.

**Comment by asticode** [comment]
ok, I will test and merge the PR if successfull.

Thanks!

**Comment by asticode** [comment]
I've just tested, and there are 3 things that went wrong:

- [this](https://github.com/lissyx/go-astideepspeech/blob/api-v0.6/deepspeech.go#L121) should be replaced with `C.CreateStream`
- mentions of `-alphabet` in the [README](https://github.com/lissyx/go-astideepspeech/blob/api-v0.6/README.md#use-the-client) should be removed since the flag has been removed
- running `deepspeech` with the audio `2830-3980-0043.wav` returns `experience proof less` instead of `experience proves this`

**Comment by lissyx** [comment]
> running `deepspeech` with the audio `2830-3980-0043.wav` returns `experience proof less` instead of `experience proves this`

I'm not sure what's the problem for that ...



>     * [this](https://github.com/lissyx/go-astideepspeech/blob/api-v0.6/deepspeech.go#L121) should be replaced with `C.CreateStream`
> 
>     * mentions of `-alphabet` in the [README](https://github.com/lissyx/go-astideepspeech/blob/api-v0.6/README.md#use-the-client) should be removed since the flag has been removed

Fixed both

**Comment by asticode** [comment]
Thanks!

**Pull request merged**
