### PR TITLE
Properly free C string

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by lissyx** [comment]
@asticode Could you have a look at that ? It should use the newly exposed `DS_FreeString()` to ensure the C string is properly free'd.

**Comment by asticode** [comment]
It seems you embarked this change in [this PR](https://github.com/asticode/go-astideepspeech/pull/9), should I close this one then?

**Comment by lissyx** [comment]
@asticode Nope I did that on purpose but left this one open since it's the same change and I figured you may prefer two different PRs.

**Comment by asticode** [comment]
I don't mind reviewing only one PR (the other one) even though I get why you opened this one as well. If you're OK with it, I'll close this PR.

**Comment by lissyx** [comment]
Let's close this then !

**Comment by asticode** [comment]
Cheers

**Pull request closed without merging**
